// All knobs are environment variables: `k6 run -e RATE=2000 -e MAX_ID=50000000 load-test.js`.

export const BASE_URL = __ENV.BASE_URL || 'http://localhost:3000';
export const API = `${BASE_URL}/api`;

/** Requests per second generated by THIS k6 instance (one VM = one instance). */
export const TOTAL_RATE = Number(__ENV.RATE || 2000);

/** Read share of that rate; the remainder are writes. */
export const READ_PERCENT = Number(__ENV.READ_PERCENT || 70);

export const READ_RATE = Math.round(TOTAL_RATE * (READ_PERCENT / 100));
export const WRITE_RATE = TOTAL_RATE - READ_RATE;

export const DURATION = __ENV.DURATION || '1m';

/**
 * A short, gentler phase before the measured one. Without it the first second
 * against a freshly started backend pays for a cold JIT and a connection pool
 * still growing from DB_POOL_MIN; that spike is big enough that k6 cannot find
 * a free VU in time and drops iterations, so the run quietly misses its target
 * rate for reasons unrelated to steady-state capacity.
 *
 * Warm-up traffic is tagged `kind:warmup` and excluded from the read/write
 * thresholds. Set WARMUP=0s to measure cold start deliberately.
 */
export const WARMUP = __ENV.WARMUP || '10s';
export const WARMUP_RATE = Number(__ENV.WARMUP_RATE || Math.max(50, Math.round(TOTAL_RATE * 0.1)));
export const WARMUP_ENABLED = WARMUP !== '0s' && WARMUP !== '0';

/**
 * The id range reads are drawn from, uniformly at random. Nothing is seeded:
 * the test runs against whatever is already in the table.
 *
 * Set MAX_ID to the real `max(id)` of your table:
 *   SELECT min(id), max(id) FROM users;
 *
 * A miss is a legitimate outcome, not a failure -- a 404 still costs a full
 * index probe, which is the work being measured. But if MAX_ID is far larger
 * than the real maximum, almost every read misses and you end up measuring
 * index misses only; setup() reports the observed hit rate so this is visible
 * rather than silent.
 */
export const MIN_ID = Number(__ENV.MIN_ID || 1);
export const MAX_ID = Number(__ENV.MAX_ID || 50000000);

/**
 * How to build an email from an id for the by-email read. The default matches
 * nothing in a real dataset -- set it to your own data's pattern, or accept
 * that every by-email read is a 404 (still a valid index-probe measurement).
 */
export const EMAIL_TEMPLATE = __ENV.EMAIL_TEMPLATE || 'user{id}@loadtest.local';

/**
 * Identifies this load generator. MUST be unique per VM when several run at
 * once, otherwise two VMs can generate the same email and collide on the
 * unique index, turning a generator artefact into a 409 that looks like a
 * server fault. Left empty, setup() assigns a random token.
 */
export const NODE_ID = __ENV.NODE_ID || '';

/**
 * Split of the read budget across the three read endpoints, in percent.
 *
 * `list` defaults to 0 on purpose. GET /api/users runs `SELECT count(*)` on
 * every call, which is a full table scan: measured at 342ms on 10M rows, and
 * roughly 1.7s on 50M. Including it does not measure the API, it measures that
 * one scan, and it will saturate the database long before the target rate is
 * reached. Enable it only once the endpoint has been fixed (see the README).
 */
export const READ_MIX = {
  byId: Number(__ENV.MIX_BY_ID || 60),
  byEmail: Number(__ENV.MIX_BY_EMAIL || 40),
  list: Number(__ENV.MIX_LIST || 0),
};

/**
 * Deepest page the list read will request. Deep offsets are O(offset) in
 * Postgres -- `OFFSET 9000000` measured at 924ms on 10M rows -- and no real
 * client pages that far, so measuring it would be an artefact.
 */
export const LIST_MAX_PAGE = Number(__ENV.LIST_MAX_PAGE || 50);

export const randomId = () => MIN_ID + Math.floor(Math.random() * (MAX_ID - MIN_ID + 1));

export const emailForId = (id) => EMAIL_TEMPLATE.replace('{id}', id);

/**
 * An arrival-rate executor needs enough VUs to cover `rate x latency`
 * (Little's law): at 2000 req/s with a 5ms response only ~10 are busy at any
 * moment. The generous multipliers are not for the steady state, they are for
 * the spikes.
 *
 * Against a large table this matters more than it looks: random reads over
 * tens of millions of rows miss the page cache and occasionally hit disk, so
 * the latency tail is far longer than the median. k6 scales VUs up lazily, and
 * every iteration that comes due while it is still scaling is *dropped* -- so
 * under-allocating here makes a run silently miss its target rate even though
 * the server was keeping up fine.
 *
 * Budgets 250ms of latency up front, and allows growth to a 1s budget.
 */
export const vusFor = (rate) => ({
  preAllocatedVUs: Math.max(50, Math.ceil(rate * 0.25)),
  maxVUs: Math.max(100, Math.ceil(rate * 1.0)),
});
